#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-assertj-parent-pom
Version  : 2.1.6
Release  : 3
URL      : https://github.com/joel-costigliola/assertj-maven-parent-pom/archive/assertj-parent-pom-2.1.6.tar.gz
Source0  : https://github.com/joel-costigliola/assertj-maven-parent-pom/archive/assertj-parent-pom-2.1.6.tar.gz
Source1  : https://repo1.maven.org/maven2/org/assertj/assertj-parent-pom/2.1.6/assertj-parent-pom-2.1.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-assertj-parent-pom-data = %{version}-%{release}

%description
A simple maven pom to gather all data common to AssertJ modules.

%package data
Summary: data components for the mvn-assertj-parent-pom package.
Group: Data

%description data
data components for the mvn-assertj-parent-pom package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/assertj/assertj-parent-pom/2.1.6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/assertj/assertj-parent-pom/2.1.6/assertj-parent-pom-2.1.6.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/assertj/assertj-parent-pom/2.1.6/assertj-parent-pom-2.1.6.pom
